### ISSUE TITLE
[BUG] String replacement with regex does not work

### ISSUE THREAD

**Issue by adarovsky** [krzysztofzablocki/SourceryPro-Feedback#22]
**Describe the bug**
A filter from StencilSwiftKit does not support regex mode

**To Reproduce**
1. Open Sourcery Pro
2. Create a new template, clean it up
3. Enter the following example: `{{ "Test string"|replace:"^.","Prefix ",regex }}`
4. Generated code reads `Test String`

**Expected behavior**
Generated code should read `Prefix est string`

**Screenshots**
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/954082/188142324-0af21640-c596-41a8-9eee-589774eb563d.png">

**Sourcery template**
[Regex bug.sourcerytemplate.zip](https://github.com/krzysztofzablocki/SourceryPro-Feedback/files/9477804/Regex.bug.sourcerytemplate.zip)

**Comment by krzysztofzablocki** [comment]
Regex is new addition to the library and will be available in next update that updates the dependency

**Comment by adarovsky** [comment]
New release just fixed that. Thank you!
