### ISSUE TITLE
[BUG] Online documentation served as text/plain

### ISSUE THREAD

**Issue by gredman** [krzysztofzablocki/SourceryPro-Feedback#24]
**Describe the bug**
Selecting “Sourcery Documentation” in the Help menu opens https://cdn.jsdelivr.net/gh/krzysztofzablocki/Sourcery@master/docs/index.html, which is served as text/plain and renders as plain text.

**To Reproduce**
1. Select “Sourcery Documentation” in the Help menu opens 

**Expected behavior**
I can read the documentation.

**Screenshots**
<img width="1549" alt="Screen Shot 2022-10-06 at 11 24 26" src="https://user-images.githubusercontent.com/608139/194175723-eba9ece1-6fbe-437d-a122-24ffd8f82397.png">

**Sourcery template**
Irrelevant

**Additional context**
None

**Comment by krzysztofzablocki** [comment]
I'm blocked from updating atm as I wait for SwiftSyntax update, the docs are here https://krzysztofzablocki.github.io/Sourcery/

**Comment by krzysztofzablocki** [comment]
I'm blocked from updating atm as I wait for SwiftSyntax update, the docs are here https://krzysztofzablocki.github.io/Sourcery/

**Comment by krzysztofzablocki** [comment]
updated appstore version, will update standalone next

**Comment by gredman** [comment]
Thanks @krzysztofzablocki !
