### ISSUE TITLE
Sourcery Pro download for existing direct purchase customers

### ISSUE THREAD

**Issue by nivanchikov** [krzysztofzablocki/SourceryPro-Feedback#26]
Some time ago, I made a direct purchase of a Sourcery Pro license from https://www.merowing.info/sourcery-pro. I am currently facing a situation where I need to re-download the application due to an OS upgrade. However, upon reviewing the website, I have noticed that my available options seem to be limited to either purchasing the app from the Mac App Store or acquiring a new license. 

Could you please guide me on how to directly download the executable for Sourcery Pro from your website or another official source? I have a valid license and am willing to provide any required information.

I tried to send an email at noreply@merowing.info, but the delivery failed.

Thanks!

**Comment by krzysztofzablocki** [comment]
@nivanchikov https://vendors.paddle.com/download/product/d3a29aca-33bd-4a65-8f88-ef6a05fd166e

**Comment by ahmediosDeveloper** [comment]
Hi @krzysztofzablocki 
i have bought Sorucery Pro from https://www.merowing.info/sourcery-pro/  (Buy Directly) not from apple Store , and my current version is 1.3.3  and i cant find away to upgrade to last version 1.3.5.
