### ISSUE TITLE
[BUG] SourvceryPRO from App Store doesn't recognise template

### ISSUE THREAD

**Issue by bilousoleksandr** [krzysztofzablocki/SourceryPro-Feedback#27]
**Describe the bug**

Old sourcery and stencil inside sourceryPro app in Mac App Store.
I would suggest to update the app with up-to-date utilities or add ability to select sourcery executable path to avoid unnecessary app updates.

**To Reproduce**
1. Go to [AutoMockable](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoMockable.stencil) template
2. Copy it to SourceryPro from MAS
3. Receive valudation error

**Expected behavior**
Template should work

**Screenshots**

**Sourcery template**
Exported template (right click on the template list) that the issue occurs in.
Template here - https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoMockable.stencil

**Additional context**

**Comment by krzysztofzablocki** [comment]
Sourcery dependency in Pro has been updated to newest, it can't use CLI as that's not allowed in extensions
