### ISSUE TITLE
macOS 15, SourceryPro doesn't open

### ISSUE THREAD

**Issue by pnewell** [krzysztofzablocki/SourceryPro-Feedback#30]
**Describe the bug**
On macOS 15 (beta 3) and when I open SourceryPro (1.3.5) the theme window opens, but not the main window. If I hit make new template nothing happens. I've tried restarting also but no luck.

**To Reproduce**
1. Instal macOS 15 (beta 3)
2. Download SourceryPro 1.3.5 from the Mac app store
3. Open SourceryPro

**Expected behavior**
Main window with editor and template list opens

**Screenshots**
<img width="480" alt="Screenshot 2024-07-17 at 8 27 43 PM" src="https://github.com/user-attachments/assets/d9afc720-e163-46c7-b076-468fb6639bc9">

**Sourcery template**
N/A

**Additional context**
N/A

**Comment by pavel-trafimuk** [comment]
The same issue

**Comment by hassila** [comment]
Same with Sequoia final release.

**Comment by croppka1** [comment]
It's still happening, any chance of fixing this issue soon @krzysztofzablocki?

**Comment by krzysztofzablocki** [comment]
I'll be taking a look this week, was traveling a lot last 2 months

**Comment by krzysztofzablocki** [comment]
1.4.0 on AppStore should fix it, I'll deploy outside appstore version soon too

**Comment by iamyogish** [comment]
Hey @krzysztofzablocki, thanks for fixing this in 1.4.0. I just wanted to ask when version 1.4 will be available for users who didn’t purchase Sourcery Pro through the App Store? Thanks! 😄

**Comment by krzysztofzablocki** [comment]
@iamyogish I'm going to push release this week, it just isn't automated so need to find my notes for doing it 😂

**Comment by krzysztofzablocki** [comment]
should be up on direct distribution now
